# docker-compose.yml
version: "3"

volumes:
  app_data:
    name: app_data
    external: true
  app_db:
    name: app_db
    external: true

services:
  app:
    restart: on-failure
    container_name: social-mail-server
    image: neurospeech/social-mail-web-server:latest
    depends_on:
      - postgres
    env_file:
      - vars.env
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
    volumes:
      - /var/lib/clamav
      - app_data:/data

  postgres:
    container_name: postgres-server
    restart: on-failure
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SocialMail2023
      POSTGRES_DB: SocialMails
      PGDATA: /data/db
    command:
      - "postgres"
      - "-c"
      - "archive_mode=on"
      - "-c"
      - "archive_command=cp %p /data/db/archive/%f"
    volumes:
      - ./app_db:/data/db
      - ./setup/setup.sh:/docker-entrypoint-initdb.d/init-database.sh
