name: Node.js CI

on: push

# on:
#   schedule:
#    - cron: '0 0 * * *'


# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: cp README.md ./build/README.md

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:build"
          push: true
          tags: neurospeech/social-mail-community-server:latest

      # - name: Delete Old Images
      #   uses: camargo/delete-untagged-action@v1
      #   with:
      #     github-token: ${{ secrets.GHCR_TOKEN }} 
